import type { LanguageCode } from './language';

/** Contracts of the ImageCards API. Mirrors the backend DTOs (see docs/api.md). */

export const REVIEW_RATINGS = ['Again', 'Hard', 'Good', 'Easy'] as const;

export type ReviewRating = (typeof REVIEW_RATINGS)[number];

export interface Translation {
  language: LanguageCode;
  translatedText: string;
  exampleSentence: string | null;
}

export interface Card {
  id: string;
  /** Temporary SAS URL generated by the backend. */
  imageUrl: string;
  createdAt: string;
  translations: Translation[];
}

/** A card ready to study in one language (GET /api/reviews/due). */
export interface Flashcard {
  id: string;
  imageUrl: string;
  translation: string;
  language: LanguageCode;
  exampleSentence: string | null;
  nextReviewAt: string;
}

export interface DueCardsResponse {
  totalDue: number;
  cards: Flashcard[];
}

/** Body of POST /api/reviews. */
export interface Review {
  cardId: string;
  rating: ReviewRating;
}

export interface ReviewState {
  cardId: string;
  nextReviewAt: string;
  lastReviewedAt: string | null;
  intervalDays: number;
  easeFactor: number;
  repetitions: number;
  lapses: number;
}

export interface PagedResponse<T> {
  items: T[];
  page: number;
  pageSize: number;
  totalCount: number;
}

/** RFC 9457 problem details returned by the API on errors. */
export interface ProblemDetails {
  type?: string;
  title?: string;
  status?: number;
  detail?: string | null;
  traceId?: string;
  errors?: Record<string, string[]>;
}
